### ISSUE TITLE
Missing header file?

### ISSUE THREAD

**Issue by gniezen** [edgeimpulse/ei-spresense-4g-wildlife-camera#1]
Hi there!

When I try to compile `wildlife-camera-sketch.ino` I get the following error:

```
Arduino: 1.8.19 (Linux), Board: "Spresense, MainCore, 1536 KB, Disabled, 115200"

4g_camera:6:10: fatal error: Wildlife_Camera_On_Device_-_North_America_inferencing.h: No such file or directory
    6 | #include <Wildlife_Camera_On_Device_-_North_America_inferencing.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Wildlife_Camera_On_Device_-_North_America_inferencing.h: No such file or directory
```
It looks like this header file may be missing from the project?

**Comment by gniezen** [comment]
@Dasch0 Any ideas?

**Comment by Dasch0** [comment]
Hey @gniezen, pardon the delayed response.

For Arduino projects with Edge Impulse, you'll need to import the Arduino library to your IDE from the project in question. This is summarized in steps 6 - 7 in the readme, but if those steps aren't working well for your environment - there's a more detailed guide here:
https://docs.edgeimpulse.com/docs/deployment/running-your-impulse-arduino

Follow while using the wildlife camera project (you will need to clone it first via the top right corner): https://studio.edgeimpulse.com/public/105811/latest
Would you try these steps and add feedback here, I can update the readme accordingly.

**Comment by gniezen** [comment]
Hi @Dasch0 ! It appears I didn't perform step (3) under "Using this project" correctly. I just tried it again and it now compiles. Thank you!
